### ISSUE TITLE
The `template.install` should first call `template.uninstall`

### ISSUE THREAD

**Issue by the-mikedavis** [pragdave/mix_templates#13]
Since `template.install` doesn't completely wipe out the `.mix/templates/<project>` directory, if you delete a template file and then `mix template.install` and `mix gen <template> ...`, the file will still be generated.

As a work-around, you can just `template.uninstall` and then `template.install`, but it'd be less of a gotcha if `template.install` did the cleaning for you.

**Comment by pragdave** [comment]
I think you're right.

Any chance of a PR?

**Comment by the-mikedavis** [comment]
Sure thing, I'll ship it along soon
