### ISSUE TITLE
Support for .eex files inside template?

### ISSUE THREAD

**Issue by tmepple** [pragdave/mix_templates#8]
I've been attempting to make templates which exactly mimic the Phoenix v1.3 generators before customizing further for my needs.

The first issue (copying binary `.png` and `.ico` files without running them through EEx) was easy to work around with the PR from @aschriewer or the fork from @cas27.

I'm not sure how it's easily possible to deal with the second issue though.  There are two `.eex` files embedded in a newly generated Phoenix project under `web/templates/layout/app.html.eex` and `web/templates/page/index.html.eex`.  When running `mix gen` it fails attempting to evaluate those files in the context of mix_templates because the files contain references to `get_flash` and `render` which only make sense in the context of a Phoenix app.

I was thinking of a workaround where `.eex` files would be added to @cas27 skip_eex list so they would simply be copied as-is but then using template functions such as `<%= @project_name_camel_case %>` and the like would no longer work.  That seems like the best (relatively easy) alternative though?

**Comment by cas27** [comment]
I would just use the double %  `<%%= render %>`
EEx would eval this too: `<%= render %>`

**Comment by tmepple** [comment]
The double % works great... didn't realize you could "escape" the EEx like that.  Thanks @cas27 really appreciate it.
